version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/opt/django-admin/static
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - SQL_HOST=db
    networks:
      - backend_nw
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - backend_nw
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/opt/django-admin/static
    ports:
      - "80:80"
    depends_on:
      web:
        condition: service_started
    networks:
      - backend_nw

volumes:
  postgres_data:
  static_volume:

networks:
  backend_nw:
    driver: bridge